### ISSUE TITLE
create docker-compose.yml

### ISSUE THREAD

**Issue by shivam221098** [shivam221098/network-attached-storage#3]
A compose file is needed that builds an image using `Dockerfile`, with two services `web` for running the server on `0.0.0.0:8000` (depends on `db`) and `db` for postgres.

**Comment by signed-log** [comment]
Can I help with that?

**Comment by shivam221098** [comment]
Hey @signed-log,

Thanks for your comments and your interest towards the issue. 🙂

It's my mistake actually I haven't closed these issues yet. These issues are done and pushed into dev_2 branch. 

Feel free to suggest any changes.

Thanks
Shivam.
